# Generated by Django 4.0.4 on 2022-06-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_log_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='is_late',
            field=models.BooleanField(null=True),
        ),
    ]
